2025-07-11 22:15:27,837 INFO    MainThread:2328689 [wandb_setup.py:_flush():80] Current SDK version is 0.21.0
2025-07-11 22:15:27,837 INFO    MainThread:2328689 [wandb_setup.py:_flush():80] Configure stats pid to 2328689
2025-07-11 22:15:27,837 INFO    MainThread:2328689 [wandb_setup.py:_flush():80] Loading settings from /home/weishu/.config/wandb/settings
2025-07-11 22:15:27,837 INFO    MainThread:2328689 [wandb_setup.py:_flush():80] Loading settings from /home/weishu/Desktop/online_adaptive_cbf/nn_model/wandb/settings
2025-07-11 22:15:27,837 INFO    MainThread:2328689 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-07-11 22:15:27,837 INFO    MainThread:2328689 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /home/weishu/Desktop/online_adaptive_cbf/nn_model/wandb/run-20250711_221527-bzsvcya0/logs/debug.log
2025-07-11 22:15:27,837 INFO    MainThread:2328689 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /home/weishu/Desktop/online_adaptive_cbf/nn_model/wandb/run-20250711_221527-bzsvcya0/logs/debug-internal.log
2025-07-11 22:15:27,837 INFO    MainThread:2328689 [wandb_init.py:init():830] calling init triggers
2025-07-11 22:15:27,837 INFO    MainThread:2328689 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'learning_rate': 1e-05, 'epochs': 500, 'batch_size': 32, '_wandb': {}}
2025-07-11 22:15:27,837 INFO    MainThread:2328689 [wandb_init.py:init():871] starting backend
2025-07-11 22:15:28,054 INFO    MainThread:2328689 [wandb_init.py:init():874] sending inform_init request
2025-07-11 22:15:28,081 INFO    MainThread:2328689 [wandb_init.py:init():882] backend started and connected
2025-07-11 22:15:28,083 INFO    MainThread:2328689 [wandb_init.py:init():953] updated telemetry
2025-07-11 22:15:28,099 INFO    MainThread:2328689 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-07-11 22:15:28,757 INFO    MainThread:2328689 [wandb_init.py:init():1029] starting run threads in backend
2025-07-11 22:15:28,823 INFO    MainThread:2328689 [wandb_run.py:_console_start():2458] atexit reg
2025-07-11 22:15:28,823 INFO    MainThread:2328689 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-07-11 22:15:28,823 INFO    MainThread:2328689 [wandb_run.py:_redirect():2375] Wrapping output streams.
2025-07-11 22:15:28,823 INFO    MainThread:2328689 [wandb_run.py:_redirect():2398] Redirects installed.
2025-07-11 22:15:28,824 INFO    MainThread:2328689 [wandb_init.py:init():1075] run started, returning control to user process
2025-07-11 22:15:28,903 INFO    MainThread:2328689 [wandb_watch.py:_watch():70] Watching
2025-07-11 22:19:53,830 INFO    MsgRouterThr:2328689 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-07-11 22:19:54,662 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:19:54,665 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:19:54,666 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:19:54,673 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:19:54,674 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:19:54,674 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:19:54,675 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:19:54,676 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:19:54,677 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:19:54,677 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:19:54,677 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:19:54,678 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:19:54,679 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:19:54,679 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:19:54,680 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:19:54,680 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:19:54,680 ERROR   MainThread:2328689 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
